### ISSUE TITLE
Microsoft.NET.Test.Sdk 17.14.1 breaks my project build

### ISSUE THREAD

**Issue by JasenHTGI** [microsoft/vstest#15113]
I have this .NET 9.0 Test project with Microsoft.NET.Test.Sdk, and it will build with 17.14.0, but if I upgrade to 17.14.1, I get an error:
1>------ Build started: Project: Tests, Configuration: Debug Any CPU ------
1>CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point

Downgrading to 17.14.0 resolves this issue right away and the project will build.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Library</OutputType>
	  <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BCNA Shipping Generator Rewrite\BCNA Shipping Generator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>

```

**Comment by Youssef1313** [comment]
@JasenHTGI Are you still hitting this? Can you please attach a binlog of the failing build?

**Comment by nohwnd** [comment]
## Triage Analysis 🤖

Thank you for the report! I looked into the `netcoreapp/Microsoft.NET.Test.Sdk.targets` file in this repo to understand what might cause this regression.

### Root Cause Hypothesis

The targets file unconditionally sets `OutputType=Exe` (unless the project is a WinUI/UWP project):

```xml
<OutputType Condition="'$(UseWinUI)' != 'true' AND '$(UseUwpTools)' != 'true'">Exe</OutputType>
```

This override happens **after** your project's properties are evaluated, so your `<OutputType>Library</OutputType>` gets replaced with `Exe`. This by itself should be fine in 17.14.0 because the package also generates a `Microsoft.NET.Test.Sdk.Program.cs` file that provides the `Main` method.

The CS5001 error (no Main method) would occur if:
1. `OutputType` is being set to `Exe` (expected behavior from the SDK), AND
2. The generated `Microsoft.NET.Test.Sdk.Program.cs` is **not** being included in compilation

### What Might Have Changed in 17.14.1

If the generated program file is not being included, this could be related to `<UseArtifactsOutput>true</UseArtifactsOutput>` interacting with how the file path is resolved, or a change in the `GenerateProgramFile` target logic.

### Questions

1. **Does this still reproduce with the latest `Microsoft.NET.Test.Sdk`?** This issue was filed a while back and a fix may have already been released.
2. If it still reproduces, can you check if adding `<GenerateProgramFile>true</GenerateProgramFile>` to your project helps?
3. Is `<UseArtifactsOutput>true</UseArtifactsOutput>` required? Does removing it fix the build?

### Workaround

If you don't need the project to produce an executable (e.g., you're using a test runner that doesn't need it), you can set:
```xml
<GenerateProgramFile>true</GenerateProgramFile>
```
or alternatively keep `OutputType` unset and let the SDK manage it.



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/25948865021)*
